#parsing details
source = "content"
output = "output"
exclude = ["drafts"]

#styling
inputdate = "yyyy MM dd"
outputdate = "MMM d yyyy"
theme = "wells"
headerimage = ""
postsperindex = 10

#render files as per tags?
rendertags = false

#preview
port = 9090

#social media details
[social]
	twitter = "thepawandubey"
	github = "pawandubey"

#site details
[site]
	name = "Not So Null"
	tagline = "Code += Play"
	author = "Pawan Dubey"
	baseurl = "https://blog.pawandubey.com"
