#parsing details
source = "content"
output = "output"
exclude = []

#styling
inputdate = "yyyy MM dd"
outputdate = "MMM d yyyy"
theme = "wells"
headerimage = ""
postsperindex = 10

#render files as per tags?
rendertags = true

#preview
port = 9090

#social media details
[social]
	disqus = "your disqus shortcode"
	fb = 
	twitter = "thepawandubey"
	github = "pawandubey"
	gplus = "PawanDubeyK"
	so = "your stackoverflow profile id"

#site details
[site]
	name = "Not So Null"
	tagline = "Code += Play"
	author = "Pawan Dubey"
	baseurl = "http://localhost:9090"
